name: Deploy Coo chan daily log

# mainブランチをpushする度にdeployする場合
# on:
#   push:
#     branches:
#       - main

# 手動トリガーでdeployする場合
on:
  workflow_dispatch:

env:
  IMAGE_NAME: asia-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coo-chan-daily-log/coo-chan-daily-log-app
  WORKLOAD_IDENTITY_PROVIDER: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/prod-pool/providers/github
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  PORT: 8080

permissions:
  id-token: write
  contents: read

jobs:
  Build-and-Push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast2-docker.pkg.dev
      - name: Build Docker image
        run: docker build --platform linux/amd64 -t ${{ env.IMAGE_NAME }}:latest -f Dockerfile .
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:latest
